//
//  StyleKit.swift
//  MyTodos
//
//  Created by René Pirringer on 31.03.16.
//  Copyright (c) 2016 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class StyleKit : NSObject {

    //// Cache

    private struct Cache {
        static let checkmark: UIColor = UIColor(red: 0.500, green: 0.500, blue: 0.500, alpha: 1.000)
    }

    //// Colors

    public class var checkmark: UIColor { return Cache.checkmark }

    //// Drawing Methods

    public class func drawCheck(done done: Bool = true) {

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRect(x: 10, y: 10, width: 24, height: 24), cornerRadius: 4)
        StyleKit.checkmark.setStroke()
        rectanglePath.lineWidth = 2
        rectanglePath.stroke()


        if (done) {
            //// Bezier Drawing
            let bezierPath = UIBezierPath()
            bezierPath.moveToPoint(CGPoint(x: 15, y: 17.49))
            bezierPath.addLineToPoint(CGPoint(x: 22.78, y: 26))
            bezierPath.addLineToPoint(CGPoint(x: 37, y: 7))
            StyleKit.checkmark.setStroke()
            bezierPath.lineWidth = 2
            bezierPath.stroke()
        }
    }

    //// Generated Images

    public class func imageOfCheck(done done: Bool = true) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(CGSize(width: 44, height: 44), false, 0)
            StyleKit.drawCheck(done: done)

        let imageOfCheck = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfCheck
    }

}
